apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policies-gatekeeper
  namespace: policies-gatekeeper
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: name, operator: In, values: ["local-cluster"]}
