apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gatekeeper-policyset
placementBindingDefaults:
  name: binding-generic
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: gatekeeper-policyset
  remediationAction: enforce
  severity: medium
  policySets:
    - gatekeeper-policyset
  standards:
    - generic
  placementPath:  
    - placement.yaml
policies:
- name: container-warn-no-ro-fs
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/container-warn-no-ro-fs
- name: container-deny-escalation
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/container-deny-escalation
- name: container-deny-latest
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/container-deny-latest
- name: container-deny-privileged
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/container-deny-privileged
- name: container-deny-privileged-if-tenant 
  categories:
    - setup
  controls: 
    - setup
  disabled: false
    - path: gatekeeper/container-deny-privileged-if-tenant    
- name: container-deny-without-resource-constraints
  categories:
    - setup
  controls: 
    - setup
  disabled: false
    - path: container-deny-without-resource-constraints
- name: pod-deny-host-alias
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/pod-deny-host-alias
- name: pod-deny-host-ipc
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/pod-deny-host-ipc
- name: pod-deny-host-network
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/pod-deny-host-network
- name: pod-deny-host-pid
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/pod-deny-host-pid
- name: disable-templates
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: gatekeeper/pod-deny-without-runasnonroot












