apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: kyverno-policyset
placementBindingDefaults:
  name: kyverno-policyset
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies-appset
  remediationAction: enforce
  severity: medium
  policySets:
    - kyverno-multitenancy
  standards:
    - generic
  placementPath:  
    - placement.yaml
policies:
- name: restrict_annotations
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_annotations
- name: restrict_automount_sa_token
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_automount_sa_token
- name: restrict-binding-clusteradmin
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict-binding-clusteradmin
- name: restrict-clusterrole-nodesproxy
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict-clusterrole-nodesproxy
- name: restrict_controlplane_scheduling
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_controlplane_scheduling
- name: restrict-escalation-verbs-roles
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict-escalation-verbs-roles
- name: restrict_ingress_classes
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_ingress_classes
- name: restrict_ingress_defaultbackend
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_ingress_defaultbackend
- name: restrict_ingress_host
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_ingress_host
- name: generateManagedClusterSetBindingblueteam-hub
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/generateManagedClusterSetBindingblueteam-hub.yaml
- name: restrict-ingress-wildcard
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict-ingress-wildcard
- name: restrict_loadbalancer
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_loadbalancer
- name: restrict_node_selection
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_node_selection
- name: restrict_pod_count_per_node
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_pod_count_per_node
- name: restrict-secret-role-verbs
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict-secret-role-verbs
- name: restrict_secrets_by_label
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_secrets_by_label
- name: restrict_secrets_by_name
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_secrets_by_name
- name: restrict-service-account
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict-service-account
- name: restrict_service_port_range
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_service_port_range
- name: restrict_usergroup_fsgroup_id
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict_usergroup_fsgroup_id
- name: restrict-wildcard-resources
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict-wildcard-resources
- name: restrict-wildcard-verbs
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrict-wildcard-verbs

















