apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: kyverno-multitenancy-policyset
placementBindingDefaults:
  name: kyverno-multitenancy
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: kyverno-multitenancy-policyset
  remediationAction: enforce
  severity: medium
  policySets:
    - kyverno-multitenancy
  standards:
    - generic
  placementPath:  
    - placement.yaml
policies:
- name: kyverno/add-labels-to-tenant
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/add-labels-to-tenant
- name: disallowplacementrules
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/disallowplacementrules
- name: generateall
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/generateall
- name: generateargocdpersmissions
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/generateargocdpersmissions
- name: generateManagedClusterSetBinding
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/generateManagedClusterSetBinding
- name: generatePlacementRules
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/generatePlacementRules
- name: disallow-placementRules
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/disallow-placementRules.yaml
- name: generatePlacementRules
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/generatePlacementRules
- name: other
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/other
- name: preventupdatesappproject
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/preventupdatesappproject
- name: restrictions
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/restrictions
- name: sharedresources
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/sharedresources
- name: validatens
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/validatens
- name: validateplacement
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: kyverno/validateplacement

















